import { test } from 'node:test';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';

test('Phase 13 portrait WebGL, demand rendering, eligibility and resource cleanup', { timeout: 90_000 }, async () => {
  const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL || undefined });
  const base = process.env.BASE_URL || 'http://127.0.0.1:3000';
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, deviceScaleFactor: 2 });
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()); });
  await page.addInitScript(() => {
    window.gpu = { draws: 0, created: 0, deleted: 0, progress: 0, force: 0 };
    const proto = WebGLRenderingContext.prototype;
    for (const kind of ['Texture', 'Buffer', 'Program', 'Shader']) {
      const create = proto[`create${kind}`];
      const remove = proto[`delete${kind}`];
      proto[`create${kind}`] = function(...args) { const result=create.apply(this,args); if(result) window.gpu.created++; return result; };
      proto[`delete${kind}`] = function(value) { if(value) window.gpu.deleted++; return remove.call(this,value); };
    }
    const locations = new WeakMap();
    const location = proto.getUniformLocation;
    proto.getUniformLocation = function(program,name) { const result=location.call(this,program,name); if(result) locations.set(result,name); return result; };
    const uniform = proto.uniform1f;
    proto.uniform1f = function(location,value) { if(locations.get(location)==='u_scroll') window.gpu.progress=value; if(locations.get(location)==='u_force') window.gpu.force=value; return uniform.call(this,location,value); };
    const draw = proto.drawArrays;
    proto.drawArrays = function(...args) { window.gpu.draws++; return draw.apply(this,args); };
  });
  const waitFrames = () => page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  try {
    await page.goto(base, { waitUntil: 'networkidle' });
    await page.waitForSelector('.hero-canvas[data-state="ready"]', { state: 'attached' });
    assert.equal(await page.locator('.hero-canvas').getAttribute('aria-hidden'), 'true');
    assert.equal(await page.locator('.hero-canvas').getAttribute('tabindex'), null);
    assert.ok(await page.locator('.hero-canvas').evaluate((e) => e.width / e.parentElement.clientWidth <= 1.51));
    assert.equal(await page.evaluate(() => window.gpu.created), 5, 'One texture, buffer, program and two shaders');
    const idle = await page.evaluate(() => window.gpu.draws);
    await page.waitForTimeout(350);
    assert.equal(await page.evaluate(() => window.gpu.draws), idle, 'No idle animation loop');
    await page.evaluate(() => scrollTo({ top: 648, behavior: 'instant' }));
    await waitFrames();
    assert.ok(await page.evaluate(() => window.gpu.progress > 0.39 && window.gpu.progress < 0.41));
    const bounds = await page.locator('.hero-portrait').boundingBox();
    await page.mouse.move(bounds.x + bounds.width * 0.6, bounds.y + bounds.height * 0.4);
    await page.waitForFunction(() => window.gpu.force > 0.99);
    await page.mouse.move(10, 100);
    await page.waitForFunction(() => window.gpu.force < 0.01);
    await page.evaluate(() => scrollTo({ top: 0, behavior: 'instant' }));
    await waitFrames();
    assert.ok(await page.evaluate(() => window.gpu.progress < 0.001), 'Reverse scroll restores the shader within the pin border offset');
    await page.evaluate(() => { Object.defineProperty(document, 'hidden', { value: true, configurable: true }); document.dispatchEvent(new Event('visibilitychange')); });
    const hidden = await page.evaluate(() => window.gpu.draws);
    await page.waitForTimeout(100);
    assert.equal(await page.evaluate(() => window.gpu.draws), hidden);
    await page.evaluate(() => { Object.defineProperty(document, 'hidden', { value: false, configurable: true }); document.dispatchEvent(new Event('visibilitychange')); });
    await page.getByRole('navigation', { name: 'Main navigation', exact: true }).getByRole('link', { name: 'contact', exact: true }).click();
    await page.waitForTimeout(350);
    const offscreen = await page.evaluate(() => window.gpu.draws);
    await page.waitForTimeout(350);
    assert.equal(await page.evaluate(() => window.gpu.draws), offscreen, 'Offscreen scene does no drawing');
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.waitForFunction(() => window.gpu.deleted === window.gpu.created);
    assert.equal(await page.locator('.hero-canvas').getAttribute('data-state'), 'fallback');
    await page.locator('#home').evaluate((e) => e.scrollIntoView({ behavior: 'instant' }));
    await page.emulateMedia({ reducedMotion: 'no-preference' });
    await page.waitForSelector('.hero-canvas[data-state="ready"]', { state: 'attached' });
    await page.getByRole('navigation', { name: 'Main navigation', exact: true }).getByRole('link', { name: 'work', exact: true }).click();
    await page.getByRole('link', { name: 'View project : StudentsMate', exact: true }).click();
    await page.waitForURL('**/work/studentsmate');
    await page.waitForFunction(() => window.gpu.deleted === window.gpu.created);
    assert.equal(await page.evaluate(() => window.gpu.deleted === window.gpu.created), true, 'Route unmount deletes every allocation');
    await page.goto(base, { waitUntil: 'networkidle' });
    await page.waitForSelector('.hero-canvas[data-state="ready"]', { state: 'attached' });
    await page.locator('.hero-canvas').evaluate((e) => e.getContext('webgl').getExtension('WEBGL_lose_context').loseContext());
    await page.waitForSelector('.hero-canvas[data-state="unavailable"]', { state: 'attached' });
    assert.equal(await page.locator('.hero-canvas').evaluate((e) => getComputedStyle(e).opacity), '0');
    assert.equal(await page.locator('.hero-portrait img').evaluate((e) => e.complete && e.naturalWidth > 0), true);
    const fallback = await browser.newPage({ viewport: { width: 1280, height: 900 } });
    await fallback.addInitScript(() => { const original=HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext=function(type,...args) { return type==='webgl' ? null : original.call(this,type,...args); }; });
    await fallback.goto(base, { waitUntil: 'networkidle' });
    await fallback.waitForSelector('.hero-canvas[data-state="unavailable"]', { state: 'attached' });
    const low = await browser.newPage({ viewport: { width: 1280, height: 900 } });
    await low.addInitScript(() => {
      Object.defineProperty(navigator, 'deviceMemory', { value: 2 });
      window.gpuAttempts = 0;
      const original = HTMLCanvasElement.prototype.getContext;
      HTMLCanvasElement.prototype.getContext = function(type, ...args) { if(type==='webgl') window.gpuAttempts++; return original.call(this,type,...args); };
    });
    await low.goto(base, { waitUntil: 'networkidle' });
    assert.equal(await low.locator('.hero-canvas').getAttribute('data-state'), 'fallback');
    assert.equal(await low.evaluate(() => window.gpuAttempts), 0);
    const mobile = await browser.newPage({ viewport: { width: 375, height: 812 }, isMobile: true, hasTouch: true });
    await mobile.goto(base, { waitUntil: 'networkidle' });
    assert.equal(await mobile.locator('.hero-canvas').getAttribute('data-state'), 'fallback');
    const noJS = await browser.newPage({ javaScriptEnabled: false, viewport: { width: 375, height: 812 } });
    await noJS.goto(base);
    assert.equal(await noJS.locator('.hero-canvas').evaluate((e) => getComputedStyle(e).opacity), '0');
    assert.deepEqual(errors, []);
  } finally { await browser.close(); }
});
